export interface Show {
  id: number;
  name: string;
  subtitle?: string;
  date: string;
  dateObj: Date;
  month: string;
  time?: string;
  venue: string;
  price?: string;
  link?: string;
  image?: string;
  partnership?: boolean;
  partnerName?: string;
}

export const shows: Show[] = [
  // ABRIL
  {
    id: 1,
    name: "POP MIND",
    subtitle: "Hits do Pop Rock",
    date: "02/04/2026",
    dateObj: new Date(2026, 3, 2),
    month: "Abril",
    time: "21h",
    venue: "Hard Rock Cafe",
    price: "R$ 40,00",
    link: "https://www.sympla.com.br/evento/popmind--hits-do-pop-rock-no-hard-rock-cafe-ribeirao-preto/3329441",
    partnership: false,
  },
  {
    id: 2,
    name: "AURAH",
    subtitle: "Clássicos do Pop Rock",
    date: "04/04/2026",
    dateObj: new Date(2026, 3, 4),
    month: "Abril",
    time: "21h",
    venue: "Hard Rock Cafe",
    price: "R$ 40,00",
    link: "https://www.sympla.com.br/evento/aurah-no-hard-rock-cafe-ribeirao-preto/3334603",
    partnership: false,
  },
  {
    id: 3,
    name: "U2 COVER RIBEIRÃO",
    subtitle: "Tributo ao U2",
    date: "18/04/2026",
    dateObj: new Date(2026, 3, 18),
    month: "Abril",
    time: "21h",
    venue: "Hard Rock Cafe",
    price: "R$ 50,00",
    link: "https://www.sympla.com.br/evento/u2-cover-ribeirao-no-hard-rock-cafe-ribeirao-preto/3354803",
    partnership: false,
  },

  // MAIO
  {
    id: 4,
    name: "MAMA PUNCH",
    date: "02/05/2026",
    dateObj: new Date(2026, 4, 2),
    month: "Maio",
    time: "21h",
    venue: "Hard Rock Cafe",
    partnership: false,
  },
  {
    id: 5,
    name: "ECHOS",
    subtitle: "Especial Pink Floyd",
    date: "09/05/2026",
    dateObj: new Date(2026, 4, 9),
    month: "Maio",
    time: "21h",
    venue: "Hard Rock Cafe",
    partnership: true,
    partnerName: "North Star Concerts",
  },
  {
    id: 6,
    name: "SPINE SHIVER",
    date: "16/05/2026",
    dateObj: new Date(2026, 4, 16),
    month: "Maio",
    time: "21h",
    venue: "Hard Rock Cafe",
    partnership: false,
  },
  {
    id: 7,
    name: "ROCK STORY",
    subtitle: "A História do Rock",
    date: "23/05/2026",
    dateObj: new Date(2026, 4, 23),
    month: "Maio",
    time: "21h",
    venue: "Hard Rock Cafe",
    price: "R$ 60,00",
    link: "https://www.sympla.com.br/evento/rock-story-no-hard-rock-cafe-ribeirao-preto/3318557",
    partnership: false,
  },
  {
    id: 8,
    name: "MID SEASON SHOW",
    subtitle: "School of Rock",
    date: "28/05/2026",
    dateObj: new Date(2026, 4, 28),
    month: "Maio",
    time: "21h",
    venue: "Hard Rock Cafe",
    partnership: false,
  },
  {
    id: 9,
    name: "RENATO QUASE RUSSO",
    date: "30/05/2026",
    dateObj: new Date(2026, 4, 30),
    month: "Maio",
    time: "21h",
    venue: "Hard Rock Cafe",
    partnership: false,
  },

  // JUNHO
  {
    id: 10,
    name: "ROTOR",
    date: "06/06/2026",
    dateObj: new Date(2026, 5, 6),
    month: "Junho",
    time: "21h",
    venue: "Hard Rock Cafe",
    partnership: false,
  },
  {
    id: 11,
    name: "SHOW DE TEMPORADA",
    subtitle: "School of Rock",
    date: "14/06/2026",
    dateObj: new Date(2026, 5, 14),
    month: "Junho",
    time: "21h",
    venue: "Vila Dionísio",
    partnership: false,
  },
  {
    id: 12,
    name: "U2 COVER RIBEIRÃO",
    subtitle: "Tributo ao U2",
    date: "20/06/2026",
    dateObj: new Date(2026, 5, 20),
    month: "Junho",
    time: "21h",
    venue: "Hard Rock Cafe",
    partnership: false,
  },
  {
    id: 13,
    name: "DYNAMITE",
    subtitle: "Scorpions Cover",
    date: "26/06/2026",
    dateObj: new Date(2026, 5, 26),
    month: "Junho",
    time: "21h",
    venue: "Hard Rock Cafe",
    partnership: false,
  },
  {
    id: 14,
    name: "BLACK JACK",
    date: "27/06/2026",
    dateObj: new Date(2026, 5, 27),
    month: "Junho",
    time: "21h",
    venue: "Hard Rock Cafe",
    partnership: false,
  },

  // JULHO
  {
    id: 15,
    name: "MACH 5",
    date: "04/07/2026",
    dateObj: new Date(2026, 6, 4),
    month: "Julho",
    time: "21h",
    venue: "Hard Rock Cafe",
    partnership: false,
  },
  {
    id: 16,
    name: "LUANA CAMARAH",
    subtitle: "Abertura: Fernando Quesada",
    date: "11/07/2026",
    dateObj: new Date(2026, 6, 11),
    month: "Julho",
    time: "21h",
    venue: "Hard Rock Cafe",
    partnership: true,
    partnerName: "North Star Concerts",
  },
  {
    id: 17,
    name: "AURAH",
    date: "17/07/2026",
    dateObj: new Date(2026, 6, 17),
    month: "Julho",
    time: "21h",
    venue: "Hard Rock Cafe",
    partnership: false,
  },
  {
    id: 18,
    name: "KISS COVER BRAZIL & BANDA SHERLOCK",
    date: "18/07/2026",
    dateObj: new Date(2026, 6, 18),
    month: "Julho",
    time: "21h",
    venue: "Hard Rock Cafe",
    partnership: false,
  },
  {
    id: 19,
    name: "LED ZEPPELIN EXPERIENCE",
    subtitle: "Chile",
    date: "24/07/2026",
    dateObj: new Date(2026, 6, 24),
    month: "Julho",
    time: "21h",
    venue: "Hard Rock Cafe",
    partnership: false,
  },
  {
    id: 20,
    name: "BLAYMORPHED",
    subtitle: "Pearl Jam Cover",
    date: "25/07/2026",
    dateObj: new Date(2026, 6, 25),
    month: "Julho",
    time: "21h",
    venue: "Hard Rock Cafe",
    partnership: true,
    partnerName: "North Star Concerts",
  },

  // AGOSTO
  {
    id: 21,
    name: "OZZMOZZY",
    subtitle: "Ozzy Cover",
    date: "01/08/2026",
    dateObj: new Date(2026, 7, 1),
    month: "Agosto",
    time: "21h",
    venue: "Hard Rock Cafe",
    partnership: true,
    partnerName: "North Star Concerts",
  },
  {
    id: 22,
    name: "ROCKER 23",
    date: "08/08/2026",
    dateObj: new Date(2026, 7, 8),
    month: "Agosto",
    time: "21h",
    venue: "Hard Rock Cafe",
    partnership: true,
    partnerName: "North Star Concerts",
  },
  {
    id: 23,
    name: "U2 COVER RIBEIRÃO",
    subtitle: "Tributo ao U2",
    date: "15/08/2026",
    dateObj: new Date(2026, 7, 15),
    month: "Agosto",
    time: "21h",
    venue: "Hard Rock Cafe",
    partnership: false,
  },
  {
    id: 24,
    name: "CAARU",
    date: "22/08/2026",
    dateObj: new Date(2026, 7, 22),
    month: "Agosto",
    time: "21h",
    venue: "Hard Rock Cafe",
    partnership: false,
  },
  {
    id: 25,
    name: "MANCHESTER",
    subtitle: "Oasis Cover",
    date: "29/08/2026",
    dateObj: new Date(2026, 7, 29),
    month: "Agosto",
    time: "21h",
    venue: "Hard Rock Cafe",
    partnership: true,
    partnerName: "North Star Concerts",
  },

  // SETEMBRO
  {
    id: 26,
    name: "MOJOBOX",
    date: "12/09/2026",
    dateObj: new Date(2026, 8, 12),
    month: "Setembro",
    time: "21h",
    venue: "Hard Rock Cafe",
    partnership: true,
    partnerName: "North Star Concerts",
  },
  {
    id: 27,
    name: "PURPLE BRAZIL TRIBUTE",
    subtitle: "Deep Purple",
    date: "19/09/2026",
    dateObj: new Date(2026, 8, 19),
    month: "Setembro",
    time: "21h",
    venue: "Hard Rock Cafe",
    partnership: true,
    partnerName: "North Star Concerts",
  },

  // OUTUBRO
  {
    id: 28,
    name: "JACK FAST",
    date: "03/10/2026",
    dateObj: new Date(2026, 9, 3),
    month: "Outubro",
    time: "21h",
    venue: "Hard Rock Cafe",
    partnership: false,
  },
  {
    id: 29,
    name: "U2 COVER RIBEIRÃO",
    subtitle: "Tributo ao U2",
    date: "10/10/2026",
    dateObj: new Date(2026, 9, 10),
    month: "Outubro",
    time: "21h",
    venue: "Hard Rock Cafe",
    partnership: false,
  },
  {
    id: 30,
    name: "BLACK DOG",
    subtitle: "Led Zeppelin Experience",
    date: "24/10/2026",
    dateObj: new Date(2026, 9, 24),
    month: "Outubro",
    time: "21h",
    venue: "Hard Rock Cafe",
    partnership: false,
  },
  {
    id: 31,
    name: "CAARU",
    date: "31/10/2026",
    dateObj: new Date(2026, 9, 31),
    month: "Outubro",
    time: "21h",
    venue: "Hard Rock Cafe",
    partnership: false,
  },

  // NOVEMBRO
  {
    id: 32,
    name: "NIRVANA COVER BRASIL",
    date: "07/11/2026",
    dateObj: new Date(2026, 10, 7),
    month: "Novembro",
    time: "21h",
    venue: "Hard Rock Cafe",
    partnership: true,
    partnerName: "North Star Concerts",
  },
  {
    id: 33,
    name: "ROTOR",
    date: "14/11/2026",
    dateObj: new Date(2026, 10, 14),
    month: "Novembro",
    time: "21h",
    venue: "Hard Rock Cafe",
    partnership: false,
  },
  {
    id: 34,
    name: "RADIO SHOW",
    date: "21/11/2026",
    dateObj: new Date(2026, 10, 21),
    month: "Novembro",
    time: "21h",
    venue: "Hard Rock Cafe",
    partnership: false,
  },
];

export const months = [
  "Abril",
  "Maio",
  "Junho",
  "Julho",
  "Agosto",
  "Setembro",
  "Outubro",
  "Novembro",
];

export const getShowsByMonth = (month: string) => {
  return shows.filter((show) => show.month === month);
};
